drop table d06_cliente cascade constraints;
drop table d06_fattura_testata cascade constraints;
drop table d06_fattura_dettaglio cascade constraints;
-- create tables

create table d06_cliente (
    id                 number generated by default on null as identity
                       constraint d06_cliente_id_pk primary key,
    codice_cliente     varchar2(20 char) not null,
    ragione_sociale    varchar2(50 char) not null,
    piva               varchar2(11 char) not null,
    indirizzo          varchar2(100 char) not null,
    codice_sdi         varchar2(6 char)
);

alter table d06_cliente add constraint d06_cliente_uk unique (codice_cliente);



create table d06_fattura_testata (
    id             number generated by default on null as identity
                   constraint d06_fattura_testata_id_pk primary key,
    cliente_id     number                   constraint d06_fattura_testata_cliente_id_fk
                   references d06_cliente not null,
    anno           number not null,
    numero         number not null,
    descrizione    varchar2(50 char) not null,
    data           date not null
);

-- table index
create index d06_fattura_testata_i1 on d06_fattura_testata (cliente_id);

alter table d06_fattura_testata add constraint d06_fattura_testata_uk unique (anno,numero);



create table d06_fattura_dettaglio (
    id                    number generated by default on null as identity
                          constraint d06_fattura_dettaglio_id_pk primary key,
    fattura_testata_id    number                          constraint d06_fattura_dettaglio_fattura_testata_id_fk
                          references d06_fattura_testata not null,
    riga                  number not null,
    descrizione           varchar2(100 char) not null,
    quantita              number not null,
    importo               number not null
);

-- table index
create index d06_fattura_dettaglio_i1 on d06_fattura_dettaglio (fattura_testata_id);

alter table d06_fattura_dettaglio add constraint d06_fattura_dettaglio_uk unique (fattura_testata_id,riga);



-- Generated by Quick SQL 1.2.9 24/07/2025, 09:22:17

/*
cliente /unique codice_cliente 
  codice_cliente vc20 /nn 
  ragione_sociale vc50 /nn
  piva vc11 /nn
  indirizzo vc100 /nn
  codice_sdi vc6 

fattura_testata /unique anno, numero
  anno num /nn
  numero num /nn
  descrizione vc50 /nn
  data d /nn
  cliente id /nn

fattura_dettaglio /unique fattura_testata_id,riga
  fattura_testata id /nn
  riga num /nn
  descrizione vc100 /nn
  quantita num /nn
  importo num /nn

# settings = {"apex":true,"db":"19c","drop":true,"prefix":"d06","pk":"IDENTITY"}

*/