-- create tables
drop table d03_marchio cascade constraints;
drop table d03_prodotto cascade constraints;

create table d03_marchio (
    id         number generated by default on null as identity
               constraint d03_marchio_id_pk primary key,
    marchio    varchar2(20 char)
);



create table d03_prodotto (
    id               number generated by default on null as identity
                     constraint d03_prodotto_id_pk primary key,
    marchio_id       number                     constraint d03_prodotto_marchio_id_fk
                     references d03_marchio not null,
    prodotto_cod     varchar2(255 char) not null,
    prodotto         varchar2(255 char) not null,
    descrizione      varchar2(1500 char),
    prezzo           number,
    tags             varchar2(400 char),
    genere           varchar2(20 char),
    data_rilascio    date,
    url_immagine     varchar2(400 char)
);

-- table index
create index d03_prodotto_i1 on d03_prodotto (marchio_id);



-- Generated by Quick SQL 1.2.9 02/07/2025, 09:03:26

/*
marchio
  marchio vc20

prodotto
  marchio id /nn
  prodotto_cod vc255 /nn
  prodotto vc255 /nn
  descrizione vc1500
  prezzo num
  tags vc400
  genere vc20
  data_rilascio d
  url_immagine vc400





 Non-default options:
# settings = {"apex":"Y","prefix":"d03","pk":"identity",drop:true}

*/