drop table d05_tipo_prodotto cascade constraints;
drop table d05_prodotto cascade constraints;
drop table d05_cliente cascade constraints;
drop table d05_fornitore cascade constraints;
drop table d05_acquisto cascade constraints;
drop table d05_vendita cascade constraints;
-- create tables

create table d05_tipo_prodotto (
    id               number default on null to_number(sys_guid(), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX') 
                     constraint d05_tipo_prodotto_id_pk primary key,
    tipo_prodotto    varchar2(50 char) not null,
    gruppo           varchar2(50 char) not null
);

alter table d05_tipo_prodotto add constraint d05_tipo_prodotto_uk unique (tipo_prodotto);



create table d05_prodotto (
    id                  number default on null to_number(sys_guid(), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX') 
                        constraint d05_prodotto_id_pk primary key,
    tipo_prodotto_id    number                        constraint d05_prodotto_tipo_prodotto_id_fk
                        references d05_tipo_prodotto not null,
    prodotto            varchar2(50 char) not null,
    prezzo_acquisto     number not null,
    prezzo_vendita      number not null
);

-- table index
create index d05_prodotto_i1 on d05_prodotto (tipo_prodotto_id);

alter table d05_prodotto add constraint d05_prodotto_uk unique (prodotto);



create table d05_cliente (
    id         number default on null to_number(sys_guid(), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX') 
               constraint d05_cliente_id_pk primary key,
    cliente    varchar2(50 char) not null,
    zona       varchar2(10 char) not null
);

alter table d05_cliente add constraint d05_cliente_uk unique (cliente);



create table d05_fornitore (
    id           number default on null to_number(sys_guid(), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX') 
                 constraint d05_fornitore_id_pk primary key,
    fornitore    varchar2(50 char) not null,
    zona         varchar2(50 char) not null
);

alter table d05_fornitore add constraint d05_fornitore_uk unique (fornitore);



create table d05_acquisto (
    id              number default on null to_number(sys_guid(), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX') 
                    constraint d05_acquisto_id_pk primary key,
    fornitore_id    number                    constraint d05_acquisto_fornitore_id_fk
                    references d05_fornitore not null,
    prodotto_id     number                    constraint d05_acquisto_prodotto_id_fk
                    references d05_prodotto not null,
    data            date not null,
    quantita        number not null
);

-- table index
create index d05_acquisto_i1 on d05_acquisto (fornitore_id);

create index d05_acquisto_i2 on d05_acquisto (prodotto_id);



create table d05_vendita (
    id             number default on null to_number(sys_guid(), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX') 
                   constraint d05_vendita_id_pk primary key,
    cliente_id     number                   constraint d05_vendita_cliente_id_fk
                   references d05_cliente not null,
    prodotto_id    number                   constraint d05_vendita_prodotto_id_fk
                   references d05_prodotto not null,
    data           date not null,
    quantita       number not null
);

-- table index
create index d05_vendita_i1 on d05_vendita (cliente_id);

create index d05_vendita_i2 on d05_vendita (prodotto_id);



-- Generated by Quick SQL 1.2.9 19/11/2025, 11:01:18

/*
tipo_prodotto /unique tipo_prodotto
  tipo_prodotto vc50 /nn 
  gruppo vc50 /nn

prodotto /unique prodotto
  prodotto vc50 /nn
  prezzo acquisto num /nn
  prezzo vendita num /nn
  tipo_prodotto id /nn

cliente /unique cliente
  cliente vc50 /nn
  zona vc10 /nn

fornitore /unique fornitore
  fornitore vc50 /nn
  zona vc50 /nn

acquisto 
  data date /nn
  fornitore id /nn
  prodotto id /nn
  quantita num /nn

vendita
  data date /nn
  cliente id  /nn
  prodotto id /nn
  quantita num /nn





 Non-default options:
# settings = {"apex":"Y","db":"19c","drop":true,"prefix":"d05"}

*/